-- ==============================================================================
-- Supabase Schema & Security Setup for Brahamjot Portfolio
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ==============================================================================

-- 0. Reusable Admin Authorization Helper Function
-- Verifies whether the active session JWT belongs to the authorized administrator.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT (auth.jwt() ->> 'email') = 'admin@brahamjot.dev';
$$;

-- Grant execution permission to authenticated and anon roles
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated;

-- ==============================================================================
-- 1. Portfolio Content Table & Hardened RLS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.portfolio_content (
  id TEXT PRIMARY KEY DEFAULT 'main_config',
  content JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.portfolio_content ENABLE ROW LEVEL SECURITY;

-- Clean up any legacy or overly permissive policies
DROP POLICY IF EXISTS "Allow public read access on portfolio_content" ON public.portfolio_content;
DROP POLICY IF EXISTS "Allow authenticated admin insert on portfolio_content" ON public.portfolio_content;
DROP POLICY IF EXISTS "Allow authenticated admin update on portfolio_content" ON public.portfolio_content;
DROP POLICY IF EXISTS "Allow only designated admin insert on portfolio_content" ON public.portfolio_content;
DROP POLICY IF EXISTS "Allow only designated admin update on portfolio_content" ON public.portfolio_content;
DROP POLICY IF EXISTS "Allow only designated admin delete on portfolio_content" ON public.portfolio_content;

-- Public read access: Anyone (visitor/recruiter) can view portfolio content
CREATE POLICY "Allow public read access on portfolio_content"
  ON public.portfolio_content
  FOR SELECT
  USING (true);

-- Admin-only write access: Strict check against admin@brahamjot.dev
CREATE POLICY "Allow only designated admin insert on portfolio_content"
  ON public.portfolio_content
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "Allow only designated admin update on portfolio_content"
  ON public.portfolio_content
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "Allow only designated admin delete on portfolio_content"
  ON public.portfolio_content
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- ==============================================================================
-- 2. Contact Messages Table & Hardened RLS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Clean up any existing policies
DROP POLICY IF EXISTS "Allow public insert on contact_messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Allow only admin select on contact_messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Allow only admin delete on contact_messages" ON public.contact_messages;

-- Public submission: Allow anonymous or authenticated visitors to submit inquiries
CREATE POLICY "Allow public insert on contact_messages"
  ON public.contact_messages
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Admin-only inbox reading: Only admin@brahamjot.dev can read recruiter inquiries
CREATE POLICY "Allow only admin select on contact_messages"
  ON public.contact_messages
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- Admin-only message deletion: Only admin@brahamjot.dev can remove inbox messages
CREATE POLICY "Allow only admin delete on contact_messages"
  ON public.contact_messages
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- Database-level 30-second submission rate limiting per email address
CREATE OR REPLACE FUNCTION public.check_contact_rate_limit()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.contact_messages
    WHERE LOWER(TRIM(email)) = LOWER(TRIM(NEW.email))
      AND created_at > NOW() - INTERVAL '30 seconds'
  ) THEN
    RAISE EXCEPTION 'Submission rate limit exceeded. Please wait 30 seconds before sending another message.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enforce_contact_rate_limit ON public.contact_messages;
CREATE TRIGGER trg_enforce_contact_rate_limit
  BEFORE INSERT ON public.contact_messages
  FOR EACH ROW
  EXECUTE FUNCTION public.check_contact_rate_limit();

-- ==============================================================================
-- 3. Storage Bucket & Hardened RLS for Resumes and Project Images
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio_assets', 'portfolio_assets', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Clean up any legacy storage policies
DROP POLICY IF EXISTS "Allow public read on portfolio_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated admin upload to portfolio_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated admin update on portfolio_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated admin delete on portfolio_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow only designated admin upload to portfolio_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow only designated admin update on portfolio_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow only designated admin delete on portfolio_assets" ON storage.objects;

-- Allow anyone to view/download public portfolio assets
CREATE POLICY "Allow public read on portfolio_assets"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'portfolio_assets');

-- Allow ONLY admin@brahamjot.dev to upload assets
CREATE POLICY "Allow only designated admin upload to portfolio_assets"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'portfolio_assets' AND
    public.is_admin()
  );

-- Allow ONLY admin@brahamjot.dev to update assets
CREATE POLICY "Allow only designated admin update on portfolio_assets"
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'portfolio_assets' AND
    public.is_admin()
  )
  WITH CHECK (
    bucket_id = 'portfolio_assets' AND
    public.is_admin()
  );

-- Allow ONLY admin@brahamjot.dev to delete assets
CREATE POLICY "Allow only designated admin delete on portfolio_assets"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'portfolio_assets' AND
    public.is_admin()
  );
